#!/usr/bin/env ruby
require 'bundler'
Bundler.require

require 'yaml'
require File.join Dir.pwd, 'lib/dedushka'

server_name = ARGV.shift

config = Hashie::Mash.new YAML.load_file "#{Dir.pwd}/servers.yml"
server = config[server_name]

ded = Dedushka.new server

begin
  ded.root do |sh|
    sh.exec! 'which curl || apt-get install -y curl', &ded.std
    sh.exec! 'which babushka || sh -c "`curl https://babushka.me/up`"', &ded.std
    sh.exec! 'babushka sources -l | grep pirj/babushka-deps || babushka sources -a pirj git://github.com/pirj/babushka-deps.git', &ded.std

    sh.exec! "sudo babushka pirj:system host_name=#{server_name} locale_name=#{server.locale}", &ded.std

    pubkey = File.new(File.join(Dir.home, '.ssh', server.sudoer.pubkey)).read
    sh.exec! "babushka --defaults 'pirj:user setup for provisioning' username=#{server.sudoer.name} key='#{pubkey}'", &ded.std
  end
rescue Net::SSH::AuthenticationFailed
  puts "root seems to be disabled"
end

ded.su do |sh|
  sh.exec! 'babushka sources -l | grep pirj/babushka-deps || babushka sources -a pirj git://github.com/pirj/babushka-deps.git', &ded.std
  sh.exec! "( which rvm || curl -L https://get.rvm.io) | bash -s stable --ruby", &ded.std
  sh.exec! "sudo babushka pirj:postgres.managed version=9.1", &ded.std
#   sh.exec! "sudo babushka zsh username=#{server.sudoer.name}", &ded.std
end

ded.su do |sh|
  sh.exec! "sudo babushka --default 'pirj:existing postgres db' username='#{server.db.user}' db_name=#{server.db.name}", &ded.std
end

# restrict ssh for deployer, use su - to log in
# override `` in ssh block, provide stout/stderr
